force-app/main/default/objects/Integration_Setting__mdt/Integration_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for integration callouts.</description>
    <label>Integration Setting</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Setting__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Http method for the callout.</description>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Setting__mdt/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>The resource URL.</description>
    <label>Resource</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Static_Value__mdt/Static_Value__mdt.object-meta.xml
<CustomObject>
    <description>Static value configuration for integration callouts.</description>
    <label>Static Value</label>
    <pluralLabel>Static Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Static_Value__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the static value is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Static_Value__mdt/fields/Integration_Setting__c.field-meta.xml
<CustomField>
    <fullName>Integration_Setting__c</fullName>
    <description>The related integration record.</description>
    <label>Integration Setting</label>
    <referenceTo>Integration_Setting__mdt</referenceTo>
    <relationshipLabel>Static Values</relationshipLabel>
    <relationshipName>Static_Values</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Static_Value__mdt/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The static value name.</description>
    <label>Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Static_Value__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of static value (header or query parameter).</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Header</fullName>
                <default>true</default>
                <label>Header</label>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Static_Value__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value for the static setting.</description>
    <label>Value</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationSettings.cls
/**
 * Base class for building HTTP requests form Integration_Setting__mdt.
 * @author Brian Zigarovich
 */
public with sharing class IntegrationSettings {

    /**
     * Builds the HTTP request.
     * @param namedCredential the named credential for the callout
     * @param settingName the setting name for the callout
     * @return the http request with the endpoint and headers set.
     */
    public static HttpRequest buildRequest(String namedCredential, String settingName) {
        HttpRequest retval = new HttpRequest();
        
        try {
            // Gets the configuration
            Integration_Setting__mdt setting = [
                SELECT 
                    Id,
                    Method__c,
                    Resource__c,
                    (SELECT Type__c, Name__c, Value__c FROM Static_Values__r WHERE Active__c = true)
                FROM Integration_Setting__mdt
                WHERE MasterLabel = :settingName
            ];

            retval.setMethod(setting.Method__c);
            retval.setEndpoint(namedCredential + setting.Resource__c);

            // Sets the headers and query parameters
            for (Static_Value__mdt sv : setting.Static_Values__r) {
                // Determines the parameter type
                switch on sv.Type__c {
                    when 'Header' {
                        retval.setHeader(sv.Name__c, sv.Value__c);
                    }
                    when 'Query' {
                        throw new RateRequestException(Label.Exception_Query_Parameter_Not_Supported);
                    }
                }
            }
        } catch (QueryException e) {
            throw new RateRequestException(Label.Exception_No_Integration_Setting, e);
        }

        return retval;
    }

    /**
     * @return a unique identifier.
     */
    public static String getUUID() {
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        return h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
    }
}